### ISSUE TITLE
Can't find rules.json file

### ISSUE THREAD

**Issue by likholat** [frnsys/retrosynthesis_planner#3]
Hello!
I'm trying to run `plan.py` script (I've taken all the steps from [readme.md](https://github.com/frnsys/retrosynthesis_planner/blob/1a53fe81e5c250999b70144a16f93cf901dd0bb4/readme.md)), but gets an error:
```
Traceback (most recent call last):
  File "plan.py", line 27, in <module>
    with open('model/rules.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model/rules.json'
```

@frnsys, could you please help me to find the `rules.json` file?
https://github.com/frnsys/retrosynthesis_planner/blob/1a53fe81e5c250999b70144a16f93cf901dd0bb4/plan.py#L21

**Comment by frnsys** [comment]
I just updated `policies.py` with the latest version, which produces that file. Unfortunately I can't remember if it works properly (it's been a very long time since I last looked at it), but hopefully it helps.

**Comment by likholat** [comment]
Yes, it helped to get the file. Thanks for the help!
